### ISSUE TITLE
`'AzureBlobFile' object has no attribute 'forced'` in `__del__` on bad file mode

### ISSUE THREAD

**Issue by Mause** [fsspec/adlfs#397]
As mentioned in title, `__del__` raises an exception if an unsupported file mode is passed to open

Reduced example:
```py
import adlfs
fs = adlfs.AzureBlobFileSystem()
obj = fs.open('adbfs://container/TPCH/tpch.duckdb', 'rb+', seekable=True)
```
results in:
```py
Traceback (most recent call last):
  File "/home/me/duckdb/dummy.py", line 9, in <module>
    obj = fs.open(f'{table_path}/TPCH/tpch.duckdb', 'rb+', seekable=True)
  File "/home/me/.local/lib/python3.10/site-packages/fsspec/spec.py", line 1135, in open
    f = self._open(
  File "/home/me/.local/lib/python3.10/site-packages/adlfs/spec.py", line 1688, in _open
    return AzureBlobFile(
  File "/home/me/.local/lib/python3.10/site-packages/adlfs/spec.py", line 1812, in __init__
    raise NotImplementedError("File mode not supported")
NotImplementedError: File mode not supported
Exception ignored in: <function AzureBlobFile.__del__ at 0x7f0db9d85b40>
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/adlfs/spec.py", line 2034, in __del__
    self.close()
  File "/home/me/.local/lib/python3.10/site-packages/adlfs/spec.py", line 1851, in close
    super().close()
  File "/home/me/.local/lib/python3.10/site-packages/fsspec/spec.py", line 1769, in close
    if not self.forced:
AttributeError: 'AzureBlobFile' object has no attribute 'forced'
```

**Comment by anjaliratnam-msft** [comment]
It appears that this issue was caused by an upstream bug in fsspec where `close()` accessed `self.forced` on a partially constructed `AzureBlobFile` object. A [fix](https://github.com/fsspec/filesystem_spec/pull/2042) for it has been implemented, so upgrading to the latest version should resolve the issue.
